module.exports = {
    PHOTOS_TABLE: process.env.PHOTOS_TABLE,
    ORIGINAL_BUCKET_NAME: process.env.ORIGINAL_BUCKET_NAME,
    THUMBNAIL_BUCKET_NAME: process.env.THUMBNAIL_BUCKET_NAME,
    USER_POOL: process.env.USER_POOL,
    USER_POOL_CLIENT: process.env.USER_POOL_CLIENT,
};
